version: '3'
services:
  frontend:
    build: ./frontend
    container_name: todo-frontend
    command: yarn start
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - api

  api:
    build: ./api
    container_name: todo-api
    command: yarn start
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - HOST=${HOST}
    depends_on:
      - db_api
    networks:
      - todo-network

  db_api:
    image: postgres:latest
    container_name: todo-db_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres-db:/data/postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - todo-network

volumes:
  postgres-db:


networks:
  todo-network:
    driver: bridge
